target("dcs213.project1.ui")
    set_kind("phony")
    add_packages("bun", {public = true})
    on_build(function(target)
        -- os.cd(target:scriptdir())
        -- os.run("bun install")
        -- os.run("bun run build")
        -- os.cp("./dist/**", target:targetdir(), {rootdir = "dist"})
        os.mkdir(target:targetdir())
        os.cp("$(scriptdir)/src/**", target:targetdir())
    end)
